all_patterns = [
    'CDL2CROWS',
    'CDL3BLACKCROWS',
    'CDL3INSIDE',
    'CDL3LINESTRIKE',
    'CDL3OUTSIDE',
    'CDL3STARSINSOUTH',
    'CDL3WHITESOLDIERS',
    'CDLABANDONEDBABY',
    'CDLADVANCEBLOCK',
    'CDLBELTHOLD',
    'CDLBREAKAWAY',
    'CDLCLOSINGMARUBOZU',
    'CDLCONCEALBABYSWALL',
    'CDLCOUNTERATTACK',
    'CDLDARKCLOUDCOVER',
    'CDLDOJI',
    'CDLDOJISTAR',
    'CDLDRAGONFLYDOJI',
    'CDLENGULFING',
    'CDLEVENINGDOJISTAR',
    'CDLEVENINGSTAR',
    'CDLGAPSIDESIDEWHITE',
    'CDLGRAVESTONEDOJI',
    'CDLHAMMER',
    'CDLHANGINGMAN',
    'CDLHARAMI',
    'CDLHARAMICROSS',
    'CDLHIGHWAVE',
    'CDLHIKKAKE',
    'CDLHIKKAKEMOD',
    'CDLHOMINGPIGEON',
    'CDLIDENTICAL3CROWS',
    'CDLINNECK',
    'CDLINVERTEDHAMMER',
    'CDLKICKING',
    'CDLKICKINGBYLENGTH',
    'CDLLADDERBOTTOM',
    'CDLLONGLEGGEDDOJI',
    'CDLLONGLINE',
    'CDLMARUBOZU',
    'CDLMATCHINGLOW',
    'CDLMATHOLD',
    'CDLMORNINGDOJISTAR',
    'CDLMORNINGSTAR',
    'CDLONNECK',
    'CDLPIERCING',
    'CDLRICKSHAWMAN',
    'CDLRISEFALL3METHODS',
    'CDLSEPARATINGLINES',
    'CDLSHOOTINGSTAR',
    'CDLSHORTLINE',
    'CDLSPINNINGTOP',
    'CDLSTALLEDPATTERN',
    'CDLSTICKSANDWICH',
    'CDLTAKURI',
    'CDLTASUKIGAP',
    'CDLTHRUSTING',
    'CDLTRISTAR',
    'CDLUNIQUE3RIVER',
    'CDLUPSIDEGAP2CROWS',
    'CDLXSIDEGAP3METHODS',
]
all_patterns_pandas_ta = ["2crows", "3blackcrows", "3inside", "3linestrike", "3outside", "3starsinsouth",
                          "3whitesoldiers", "abandonedbaby", "advanceblock", "belthold", "breakaway",
                          "closingmarubozu", "concealbabyswall", "counterattack", "darkcloudcover", "doji",
                          "dojistar", "dragonflydoji", "engulfing", "eveningdojistar", "eveningstar",
                          "gapsidesidewhite", "gravestonedoji", "hammer", "hangingman", "harami",
                          "haramicross", "highwave", "hikkake", "hikkakemod", "homingpigeon",
                          "identical3crows", "inneck", "inside", "invertedhammer", "kicking", "kickingbylength",
                          "ladderbottom", "longleggeddoji", "longline", "marubozu", "matchinglow", "mathold",
                          "morningdojistar", "morningstar", "onneck", "piercing", "rickshawman",
                          "risefall3methods", "separatinglines", "shootingstar", "shortline", "spinningtop",
                          "stalledpattern", "sticksandwich", "takuri", "tasukigap", "thrusting", "tristar",
                          "unique3river", "upsidegap2crows", "xsidegap3methods"]
